import { UserProfile } from './types';

export const mockProfiles: UserProfile[] = [
  {
    id: '1',
    name: 'Priya',
    surname: 'Sharma',
    age: 26,
    gender: 'Female',
    tier: 'Premium',
    photoUrl: 'https://picsum.photos/seed/priya/400/500',
    education: ['MBA, IIM Bangalore'],
    job: 'Product Manager',
    location: 'Mumbai',
    religion: 'Hindu',
    caste: 'Brahmin',
    gotra: 'Vatsa',
    height: '5\'5"',
    income: '25 - 50 LPA',
    netWorth: '1 - 5 Cr',
    dob: '1998-05-12',
    birthTime: '10:30',
    birthPlace: 'Mumbai',
    familyBackground: 'Respectable business family',
    fatherJob: 'Businessman',
    motherJob: 'Homemaker',
    siblings: '1 Brother',
    familyDetails: 'Nuclear family',
    hasDisability: 'None',
    createdBy: 'Self',
    phone: '+91 9876543210',
    email: 'priya@example.com',
    documents: {
      photo: 'uploaded',
      aadhaar: 'uploaded',
      pan: 'uploaded',
      dl: 'uploaded',
      passport: 'uploaded',
    },
    approvalStatus: 'Approved',
    loginReady: true,
    registeredAt: '2026-04-10T10:00:00Z',
    password: 'password123',
  },
  {
    id: '2',
    name: 'Aditya',
    surname: 'Varma',
    age: 29,
    gender: 'Male',
    tier: 'Elite',
    photoUrl: 'https://picsum.photos/seed/aditya/400/500',
    education: ['MS, Stanford University'],
    job: 'Founder, Tech Startup',
    location: 'Delhi',
    religion: 'Hindu',
    caste: 'Kshatriya',
    gotra: 'Kaushik',
    height: '6\'0"',
    income: '> 1 Cr',
    netWorth: '20 - 100 Cr',
    dob: '1995-08-22',
    birthTime: '14:15',
    birthPlace: 'Delhi',
    familyBackground: 'Political and business legacy',
    fatherJob: 'Retired IAS',
    motherJob: 'Social Worker',
    siblings: 'None',
    familyDetails: 'Prominent family',
    hasDisability: 'None',
    createdBy: 'Parents',
    phone: '+91 9999988888',
    email: 'aditya@example.com',
    isManager: true,
    documents: {
      photo: 'uploaded',
      aadhaar: 'uploaded',
      pan: 'uploaded',
      dl: 'uploaded',
      passport: 'uploaded',
    },
    approvalStatus: 'Approved',
    loginReady: true,
    registeredAt: '2026-04-12T14:30:00Z',
    password: 'aditya_pass',
  },
  {
    id: '3',
    name: 'Rahul',
    surname: 'Gupta',
    age: 28,
    gender: 'Male',
    tier: 'Standard',
    photoUrl: 'https://picsum.photos/seed/rahul/400/500',
    education: ['B.Tech, IIT Delhi'],
    job: 'Software Engineer',
    location: 'Bangalore',
    religion: 'Hindu',
    caste: 'Vaishya',
    gotra: 'Kashyap',
    height: '5\'10"',
    income: '10 - 25 LPA',
    netWorth: '< 1 Cr',
    dob: '1996-12-30',
    birthTime: '18:45',
    birthPlace: 'Chandigarh',
    familyBackground: 'Middle-class service family',
    fatherJob: 'Bank Manager',
    motherJob: 'Teacher',
    siblings: '2 Sisters',
    familyDetails: 'Extended family',
    hasDisability: 'None',
    createdBy: 'Self',
    phone: '+91 8888877777',
    email: 'user@example.com', // Match the demo user
    documents: {
      photo: 'uploaded',
      aadhaar: 'uploaded',
      pan: 'uploaded',
      dl: 'uploaded',
      passport: 'uploaded',
    },
    approvalStatus: 'Approved',
    loginReady: true,
    registeredAt: '2026-04-15T09:15:00Z',
    password: '12345',
  }
];
