import { UserProfile } from './types';

export const mockProfiles: UserProfile[] = [
  {
    id: '1',
    name: 'Priya',
    surname: 'Sharma',
    age: 26,
    gender: 'Female',
    tier: 'Normal',
    photoUrl: 'https://picsum.photos/seed/priya/400/500',
    education: ['MBA, IIM Bangalore'],
    job: 'Product Manager',
    location: 'Mumbai',
    religion: 'Hindu',
    caste: 'Brahmin',
    gotra: 'Vatsa',
    height: '5\'5"',
    income: '25 - 50 LPA',
    netWorth: '1 - 5 Cr',
    dob: '1998-05-12',
    birthTime: '10:30',
    birthPlace: 'Mumbai',
    familyBackground: 'Respectable business family',
    fatherJob: 'Businessman',
    motherJob: 'Homemaker',
    siblings: '1 Brother',
    familyDetails: 'Nuclear family',
    hasDisability: 'None',
    createdBy: 'Self',
    phone: '+91 9876543210',
    email: 'priya@example.com',
    documents: {
      photo: 'uploaded',
      aadhaar: 'uploaded',
      pan: 'uploaded',
      dl: 'uploaded',
      passport: 'uploaded',
    },
    approvalStatus: 'Approved',
    loginReady: true,
  },
  {
    id: '2',
    name: 'Aditya',
    surname: 'Varma',
    age: 29,
    gender: 'Male',
    tier: 'Elite',
    photoUrl: 'https://picsum.photos/seed/aditya/400/500',
    education: ['MS, Stanford University'],
    job: 'Founder, Tech Startup',
    location: 'Delhi',
    religion: 'Hindu',
    caste: 'Kshatriya',
    gotra: 'Kaushik',
    height: '6\'0"',
    income: '> 1 Cr',
    netWorth: '20 - 100 Cr',
    dob: '1995-08-22',
    birthTime: '14:15',
    birthPlace: 'Delhi',
    familyBackground: 'Political and business legacy',
    fatherJob: 'Retired IAS',
    motherJob: 'Social Worker',
    siblings: 'None',
    familyDetails: 'Prominent family',
    hasDisability: 'None',
    createdBy: 'Parents',
    phone: '+91 9999988888',
    email: 'aditya@example.com',
    isManager: true,
    documents: {
      photo: 'uploaded',
      aadhaar: 'uploaded',
      pan: 'uploaded',
      dl: 'uploaded',
      passport: 'uploaded',
    },
    approvalStatus: 'Approved',
    loginReady: true,
  }
];
